name: Java CI with Gradle

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "*" ] # ignore all tags, tags must only be used to publish release

  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.7.0
      with:
        arguments: build --scan
  publish:
    needs: [ build ]
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/publish.yml
    secrets:
      password: ${{ secrets.GPG_PASS_PHRASE }}
      key: ${{ secrets.GPG_SECRET_KEY }}
      mavenUsername: ${{ secrets.OSSRHUSERNAME }}
      mavenPassword: ${{ secrets.OSSRHPASSWORD }}
